version: '2'
services:
  mysql:
    container_name: wexort-dev-mysql
    restart: always
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: 'wexort'
      MYSQL_USER: 'wexort'
      MYSQL_PASS: 'wexort'
    ports:
      - "3306:3306"
    volumes:
      - wexort-dev-mysql:/var/lib/mysql
volumes:
  wexort-dev-mysql:
